import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign in",
  description: "Generated by create next app",
};

const Layout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <>
      {children}
    </>
  );
};

export default Layout;